version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: marikdockerid/devlabs:compose-django
    container_name: django 
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monit
    image: marikdockerid/lab4-examples:compose-monitoring
    container_name: monitoring
    network_mode: "host"
